import streamlit as st
st.header("API Integration Specialist")
st.write("API Integration Specialist are the technical problem solver who will help the clients and partners integrate with their system.  The ideal candidate should  be comfortable with writing scripts, have a strong understanding of REST web-services, and be willing to specialize in the more technical nuts and bolts of our system and the Application Programming Interface (API). Beyond the technical skillset, someone who can communicate clearly both orally and in writing. The incumbent will be required to bridge the gap between business resources and the technology team and effectively communicate with internal and external clients.")
st.subheader("Skills required")
st.write("Proven track record in understanding an enterprise’s APIs and processes.")
st.write("Experience in using APIs and web services to integrate systems.")
st.write("Excellent verbal and written communication skills, strong troubleshooting, problem solving, and analytical ability required.")
st.write("Ability to understand and articulate technical concepts and derive solutions.")
st.write("Ability to deal with complex and challenging client issues.")
st.write("Capability to perform in a high pressure working environment.")
st.subheader("Educational Requirements")
st.write("Degree in Computer Science or Information Technology or Business Information Systems or 2 years working in a technical role with API.")
st.subheader("Duties and Responsibilities")
st.write("Field support calls and emails from developers and business users about account API integration and functionality.")
st.write("Assist customers, partners, vendors and others with all aspects of our API and its documentation.")
st.write("Assist non-technical users in potential outcomes that can be achieved using the API.")
st.write("Consult business professionals on ways to maximize our API by providing data to 3rd party integrations.")
st.write("Engage with product and development teams in software development discussions to create/improve our systems.")
st.write("Use the API to create test scenarios and scripts with expected outcomes for new integrations or expanded API use.")