import streamlit as st
st.header("Application Support Engineer")
st.write("An Application Support Engineer is an IT professional who provides technical support regarding a spectrum of software used within a specific business sector. Due to this broad definition, the core responsibilities of an Application Support Engineer vary depending on the industry. Some Application Support Engineers are responsible for database management, while others put more emphasis on the programming end of an application. The specific focus is dependent on the needs of the business.Typically part of an IT support team, an Application Support Engineer needs both technical knowledge and “people” skills to do their job well. Given how interwoven technology and the business world have become, Application Support Engineers are employed internally by a number of companies across a wide spectrum of industries. Application Support Engineers can also work for an agency and have several different clients. When it comes to work environment, Application Support Engineers often collaborate with other team members, as well as customers.")
st.subheader("Skills required")
st.write("A successful Application Support Engineer is not your stereotypical anti-social tech person. In addition to possessing a wealth of technical knowledge, they must also have the interpersonal skills to help users of said application. Based on our research, we identified the following core skills one must possess to get a job as an Application Support Engineer.")
st.write("1. Working knowledge of SQL Databases & basic network configuration")
st.write("2. Working Knowledge of IT Hardware and Software")
st.write("3. Ability to learn and master employer-specific software")
st.write("4. Complex problem solving")
st.write("5. Written and verbal communication skills")
st.write("6. Ability to diagnose & address application issues")
st.subheader("Educational Requirements")
st.write("In order to get a job as an Application Support Engineer, one must first earn a Bachelor’s degree in Computer Science or a related field, such as Software Development. During the course of this education, aspiring Application Support Engineers learn the basics of database management, application development and and computer-related Mathematics.")
st.subheader("Duties and Responsibilities")
st.write("The role of Application Support Engineer is one of the more generalized positions in the IT world. A good Application Support Engineer needs to have at least a working knowledge of database management, different operating systems and different programming languages. We scoured several Application Support Engineer job postings in order to compile the following list of core responsibilities.")
st.write("1. Identifying and Evaluate Technology Solutions.")
st.write("2. Problem Solve and Troubleshoot.")
st.write("3. Onboard New Users")
st.write("4. Identify Potential Issues")
st.write("5. Work with Cross-Functional Teams")
