import streamlit as st
st.header("Business Analyst")
st.write("Business analyst help guide businesses in improving processes, products, services and software through data analysis. These agile workers straddle the line between IT and the business to help bridge the gap and improve efficiency.")
st.write("BAs are responsible for creating new models that support business decisions by working closely with financial reporting and IT teams to establish initiatives and strategies to improve importing and to optimize costs. You’ll need a “strong understanding of regulatory and reporting requirements as well as plenty of experience in forecasting, budgeting and financial analysis combined with understanding of key performance indicators,” according to Robert Half Technology.")
st.write("The role of a business analyst is constantly evolving and changing — especially as companies rely more on data to advise business operations. Every company has different issues that a business analyst can address, whether it’s dealing with outdated legacy systems, changing technologies, broken processes, poor client or customer satisfaction or siloed large organizations.")
st.subheader("Skills required")
st.write("The business analyst position requires both hard skills and soft skills. Business analysts need to know how to pull, analyze and report data trends, and be able to share that information with others and apply it on the business side. Not all business analysts need a background in IT as long as they have a general understanding of how systems, products and tools work. Alternatively, some business analysts have a strong IT background and less experience in business, and are interested in shifting away from IT to this hybrid role.")
st.write("Able to exercise independent judgment and take action on it")
st.write("Excellent analytical, mathematical, and creative problem-solving skills")
st.write("Excellent listening, interpersonal, written, and oral communication skills")
st.write("Logical and efficient, with keen attention to detail")
st.write("Highly self-motivated and directed")
st.write("Ability to effectively prioritize and execute tasks while under pressure")
st.write("Strong customer service orientation")
st.write("Experience working in a team-oriented, collaborative environment")
st.subheader("Educational Requirements")
st.write("College diploma or university degree in the field of business administration, finance, or information systems, computer science or a related field")
st.write("Proven experience with business and technical requirements analysis, elicitation, modeling, verification, and methodology development")
st.write("Excellent listening, interpersonal, written, and oral communication skills")
st.write("Demonstrated project management skills and project management software skills, including planning, organizing, and managing resources")
st.write("Working knowledge of Windows office systems")
st.write("Excellent understanding of the organization’s goals and objectives")
st.subheader("Duties and Responsibilities")
st.write("Elicits, analyzes, specifies, and validates the business needs of stakeholders, be they customers or end users. Collaborates with project sponsors to determine project scope and vision.")
st.write("Clearly identifies project stakeholders and establish customer classes, as well as their characteristics.")
st.write("Works with stakeholders and project team to prioritize collected requirements.")
st.write("Researches, reviews, and analyzes the effectiveness and efficiency of existing requirements-gathering processes and develop strategies for enhancing or further leveraging these processes.")
st.write("Develops and utilizes standard templates to accurately and concisely write requirements specifications.")
st.write("Analyzes and verifies requirements for completeness, consistency, comprehensibility, feasibility, and conformity to standards.")
st.write("Creates process models, specifications, diagrams, and charts to provide direction to developers and/or the project team.")
st.write("Manages and tracks the status of requirements throughout the project lifecycle; enforce and redefine as necessary.")
st.subheader("Salary")
st.write("The average salary for an IT business analyst is $67,762 per year, according to data from PayScale. The highest paid BAs are in San Francisco, where the average salary is 28 percent higher than the national average. New York is second, with reported salaries 18 percent higher than the national average; Boston comes in third, with a 7 percent higher annual pay.")