import streamlit as st
st.header("Cyber Security Specialist")
st.write("Cyber Security Specialist is responsible for providing security during the development stages of software systems, networks and data centers. The professionals have to search for vulnerabilities and risks in hardware and software. They manage and monitor any attacks and intrusions. The Security Specialist has to recognize the potential threat or attempted breach by closing off the security vulnerability. They build firewalls into network infrastructures.")
st.write("The Cyber Security Specialist takes care of the day-to-day operations and data structures by overseeing the operational performance. They configure anti-virus systems and consoles. The professionals must have an in-depth understanding of vulnerabilities management systems and common security applications. They conduct software upgrades and explains performance criteria, documents configurations, and systems specifications. They manage the PPC system from threats and identifies and manages incidents and mitigate risks.")
st.write("The Cyber Security Specialist takes care of the cyber security projects and makes sure they meet cyber security objectives. They work in close coordination with the stakeholders and other groups related to Cyber Security related matters. The specialist offers cyber security operations such as process re-engineering, automation, and documentation. The professionals recognize cyber security issues, devise and drive effective mitigation.")
st.subheader("Skills required")
st.write("The Cyber Security Specialist assists in designing and developing security features for system architectures. They have to play an active role in developing special purpose systems necessary for specialized security features and procedures. The specialist defines security requirements for computer systems such as mainframes, workstation, and personal computers. They have to suggest various solutions and implement them to meet the security requirements.")
st.write("Strong IT skills and knowledge including hardware, software and networks")
st.write("Meticulous attention to detail")
st.write("Ability to use logic and reasoning to identify the strengths and weaknesses of IT systems")
st.write("A forensic approach to challenges")
st.write("A deep understanding of how hackers work and ability to keep up with the fast pace of change in the criminal cyber-underworld")
st.write("Ability to seek out vulnerabilities in IT infrastructures")
st.subheader("Educational Requirements")
st.write("The Cyber Security Specialist must have a bachelor’s degree in Computer Science, Information Technology, Telecommunications, Electronics & Electrical or any related field. Some organizations prefer candidates with prior and relevant work experience, whereas some employers opt for professionals with a master’s degree or any specialization.")
st.subheader("Duties and Responsibilities")
st.write("Identifying potential security risks")
st.write("Designing strategies and defensive systems against intruders")
st.write("Monitoring systems for unusual activities (e.g. unauthorized access, modification, duplication, or destruction of information)")
st.write("Creating new layers of protection")
st.write("Updating security systems")
st.write("Running diagnostics on information changes to check for undetected breaches that may have occurred.")
st.write("Keeping up-to-date on trends and new procedures in the industry")
st.write("Taking the necessary precautions, updating and fortifying defenses accordingly")
st.subheader("Salary")
st.write("The salary of a cyber security analyst begins at Rs 6 lakhs per annum.")