import streamlit as st
st.header("Database Administrator")
st.write("Database administrators (DBAs) design, write and take care of computer database systems so that the right person can get the information they need at the right time. Database administrators or managers create and maintain databases compatible with their companies’ needs. These information technology (IT) professionals oversee database updates, storage, security, and troubleshooting. Database administrators also back up, restore, and troubleshoot database sets and system access, updating and integrating old programs to implement the latest technology.Database administrators need at least a bachelor’s degree in information science or computer science for most entry-level positions. Depending on the size and complexity of their company or governing body, these professionals may need a master’s degree in database administration or information technology. All database administrators need fundamental knowledge of structured query language (SQL) and software vendor certifications.")
st.subheader("Skills required")
st.write("1. Good communication, teamwork and negotiation skills")
st.write("2. Familiarity with the main data manipulation languages and the principles of database design")
st.write("3. The ability to work to tight deadlines under pressure")
st.write("4. Basic understanding of disaster recovery and database backup procedures")
st.write("5. A willingness to keep up to date with developments in new technology")
st.write("6. An understanding of information legislation, such as the Data Protection Act.")
st.subheader("Educational Requirements")
st.write("1. Bachelor’s Degree in Computer Science or Computer Engineering")
st.write("2. Advanced knowledge of database structure and theory")
st.write("3. Experience with MySQL and MSSQL")
st.write("4. All database administrators need fundamental knowledge of structured query language (SQL) and software vendor certifications.")
st.subheader("Duties and Responsibilities")
st.write("1. Establish the needs of users and monitor user access and security")
st.write("2. Monitor performance and manage parameters in order to provide fast responses to front-end users")
st.write("3. Map out the conceptual design for a planned database")
st.write("4. Consider both back-end organisation of data and front-end accessibility for end-users")
st.write("5. Further refining the physical design to meet system storage requirements")
st.write("6. Install and test new versions of the database management system")
st.write("7. Develop, manage and test back-up and recovery plans")
st.write("8. Work closely with IT project managers, database programmers and multimedia programmers")
