import streamlit as st
st.header("Data Scientist")
st.write("A data scientist is someone who makes value out of data. Such a person proactively fetches information from various sources and analyzes it for better understanding about how the business performs, and to build AI tools that automate certain processes within the company.")
st.write("Data scientist duties typically include creating various machine learning-based tools or processes within the company, such as recommendation engines or automated lead scoring systems. People within this role should also be able to perform statistical analysis.")
st.subheader("Skills required")
st.writer("A strong background in math, science, and computer science is a must for aspiring hardware engineers. They also, however, should be adept communicators capable of conveying instructions in verbal and written forms. Other critical skills include")
st.write("excellent analytical and problem-solving skills")
st.write("experience in database interrogation and analysis tools, such as Hadoop, SQL and SAS")
st.write("exceptional communication and presentation skills in order to explain your work to people who don't understand the mechanics behind data analysis")
st.write("planning, time management and organisational skills")
st.write("the ability to deliver under pressure and to tight deadlines")
st.write("teamworking skills and a collaborative approach to sharing ideas and finding solutions.")
st.subheader("Educational Requirements")
st.write("BSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred.")
st.write("You'll be expected to know some programming languages such as R, Python, SQL, C or Java and have strong database design and coding skills.")
st.write("A postgraduate qualification, such as a Masters or PhD, can be useful and many data scientists have one. It is especially helpful if you're considering a change of career or are interested in learning analysis skills.")
st.write("You'll typically need a mathematical, engineering, computer science or scientific-related degree to get a place on a course, although subjects such as business, economics, psychology or health may also be relevant if you have mathematical aptitude and basic programming experience.")
st.write("Understanding of machine-learning and operations research")
st.write("Strong math skills (e.g. statistics, algebra)")
st.subheader("Duties and Responsibilities")
st.write("Identify valuable data sources and automate collection processes")
st.write("Undertake preprocessing of structured and unstructured data")
st.write("Analyze large amounts of information to discover trends and patterns")
st.write("Build predictive models and machine-learning algorithms")
st.write("Combine models through ensemble modeling")
st.write("Present information using data visualization techniques")
st.write("Propose solutions and strategies to business challenges")
st.write("Collaborate with engineering and product development teams")
st.subheader("Salary")
st.write("An entry-level Data Scientist with less than 1 year experience can expect to earn an average total compensation (includes tips, bonus, and overtime pay) of ₹536,700 based on 539 salaries. An early career Data Scientist with 1-4 years of experience earns an average total compensation of ₹786,214 based on 2,351 salaries. A mid-career Data Scientist with 5-9 years of experience earns an average total compensation of ₹1,393,592 based on 814 salaries. An experienced Data Scientist with 10-19 years of experience earns an average total compensation of ₹1,747,802 based on 212 salaries. In their late career (20 years and higher), employees earn an average total compensation of ₹1,100,000.")