import streamlit as st
st.header("Graphic Designer")
st.write("The Graphic Designer job includes the entire process of defining requirements, visualizing and creating graphics including illustrations, logos, layouts and photos. Graphic Designer will be the one to shape the visual aspects of websites, books, magazines, product packaging, exhibitions and more.")
st.write("Graphic Designer should capture the attention of those who see them and communicate the right message. For this, one need to have a creative flair and a strong ability to translate requirements into design. The goal is to inspire and attract the target audience.")
st.subheader("Skills required")
st.write("Proven graphic designing experience.")
st.write("A strong portfolio of illustrations or other graphics.")
st.write("Familiarity with design software and technologies (such as InDesign, Illustrator, Dreamweaver, Photoshop).")
st.write("A keen eye for aesthetics and details.")
st.write("Excellent communication skills.")
st.write("Ability to work methodically and meet deadlines.")
st.subheader("Educational Requirements")
st.write("While entry is open to non-graduates, preference is given to those with relevant degrees. A degree in graphic design is advantageous or Degree in Design, Fine Arts or related field is a plus. Also one should have good knowledge of design software, such as Quark Xpress, InDesign or Illustrator, plus photo-editing software such as PhotoShop")
st.subheader("Duties and Responsibilities")
st.write("Study design briefs and determine requirements.")
st.write("Schedule projects and define budget constraints.")
st.write("Conceptualize visuals based on requirements.")
st.write("Prepare rough drafts and present ideas.")
st.write("Develop illustrations, logos and other designs using software or by hand.")
st.write("Use the appropriate colors and layouts for each graphic.")
st.write("Work with copywriters and creative director to produce final design.")
st.write("Ensure final graphics and layouts are visually appealing and on-brand.")
st.subheader("Salary")
st.write("The average salary for a Graphic Designer in India is Rs. 305123 per annum.")