import streamlit as st
st.header("Hardware Engineer")
st.subheader("Description")
st.write("Hardware engineers design the technology of the future. Using their solid knowledge of computer components and how they function, these skilled professionals play an important role in the development of a variety of useful products. They may, for instance, create new video game consoles, make improvements to mobile phones, or develop intelligent automotive systems. Hardware engineers frequently work full time in research labs and high-tech manufacturing firms, usually in large metropolitan areas. Some find positions in academia or with the federal government. The career path of a hardware engineer may lead to becoming a senior hardware design engineer, a computer and information systems manager, or a design engineering manager.")
st.subheader("Skills Required")
st.write("A strong background in math, science, and computer science is a must for aspiring hardware engineers. They also, however, should be adept communicators capable of conveying instructions in verbal and written forms. Other critical skills include")
st.write("1. Teamwork ")
st.write("2. Creativity")
st.write("3. Problem-solving skills")
st.write("4. Analytic thinking")
st.write("5. Multitasking")
st.subheader("Educational Qualification")
st.write("The minimum educational requirement is generally a bachelor’s degree in computer engineering or a similar discipline, though a master’s degree can increase job prospects. Graduating from a school with an ABET-accredited program also may attract a hiring manager’s attention. For hardware engineers looking to move into leadership positions, obtaining an MBA can be a smart move. All in this field should be prepared to continue taking classes throughout their career in order to stay up to date on technological advances.")
st.subheader("Duties and Responsibilities")
st.write("Design Hardware")
st.write("Test and Document Progress")
st.write("Collaborate with Colleagues")
st.subheader("Salary")
st.write("An entry-level Computer Hardware Engineer with less than 1 year experience can expect to earn an average total compensation (includes tips, bonus, and overtime pay) of ₹256,973 based on 34 salaries. An early career Computer Hardware Engineer with 1-4 years of experience earns an average total compensation of ₹197,626 based on 83 salaries. A mid-career Computer Hardware Engineer with 5-9 years of experience earns an average total compensation of ₹293,614 based on 47 salaries. An experienced Computer Hardware Engineer with 10-19 years of experience earns an average total compensation of ₹253,148 based on 34 salaries. In their late career (20 years and higher), employees earn an average total compensation of ₹394,840.")