import streamlit as st
st.header("Helpdesk Engineer")
st.subheader("Description")
st.write("Helpdesk Engineer are the go-to people for providing technical assistance and support related to computer systems, hardware, and software. They are responsible for answering queries and addressing system and user issues in a timely and professional manner. Helpdesk Engineer works with the IT team, and will often interact with system and computer users across the company. The helpdesk team will train users on basic system and computer functions. Understanding and proactively maintaining daily system performance, having the ability to troubleshoot customer problems, and innate follow-up and follow-through skills are all essential aspects of the help desk support’s day-to-day role")
st.write("An excellent Helpdesk Engineer must have good technical knowledge and be able to communicate effectively to understand the problem and explain its solution. They must also be customer-oriented and patient to deal with difficult customers. The goal is to create value for clients that will help preserve the company’s reputation and business")
st.subheader("Skills Required") 
st.write("Proven experience as a help desk technician or other customer support role.")      
st.write("Tech savvy with working knowledge of office automation products, databases and remote control")
st.write("Good understanding of computer systems, mobile devices and other tech products")
st.write("Ability to diagnose and resolve basic technical issues.") 
st.write("Proficiency in English") 
st.write("General awareness of computer systems, PC repair, and network management") 
st.subheader("Educational Background")
st.write("A college degree is required for entry-level helpdesk positions, a degree in computer information science, or help desk administration. It can also be useful to get a specialized or niche certificate in PC repair, network administration, or help desk support")   
st.subheader("Duties and Responsibilities")   
st.write("Monitor and respond quickly to incoming requests relate to IT issues") 
st.write("Serve as the first point of contact for customers seeking technical assistance over the phone or email")       
st.write("Perform remote troubleshooting through diagnostic techniques and pertinent questions")
st.write("Determine the best solution based on the issue and details provided by customers.")
st.write("Provide accurate information on IT products or services.")
st.write("Identify and suggest possible improvements on procedures.")
st.subheader("Salary")
st.write("Helpdesk Engineer salary in India ranges between ₹ 1.4 Lakhs to ₹ 4.7 Lakhs with an average annual salary of ₹ 2.4 Lakhs.")