import streamlit as st
st.header("Information Security")
st.write("Information Security Specialist role involves in understanding and taking steps to mitigate the risks associated with collecting, storing and transmitting data in a business setting. Information Security Specialist will be expected to set up security measures that help prevent security breaches, as well as analyzing any breeches that do occur.")
st.write("Information Security Specialist responsible for designing, testing and Implementation of IT Security solutions as well as on-going maintenance and monitoring of live production environments. The work may involve maintaining security software and integrating new security into an organisation using various tools and techniques including firewalls, spyware, malware detection and intrusion detection systems.")
st.subheader("Skills required")
st.write("Knowledge of current security risks and protocols.")
st.write("Willingness to work on-call in the event of a security breech or other emergency.")
st.write("Good analytic and problem solving skills.")
st.write("Understanding of relevant scripting and source code programming languages, such as C#, C++, .NET, Java, Perl, PHP, Python or Ruby On Rails etc. that you will be using")
st.subheader("Educational Requirements")
st.write("The Information Security Specialist must have a Bachelors degree in a related field such as Computer Science, IT or a Cyber-Security related field. Also Post-secondary degree in system administration, network security, network administration or a related field will be accepted.")
st.subheader("Duties and Responsibilities")
st.write("Analyze existing security systems and make recommendations for changes or improvements.")
st.write("Prepare reports and action plans in the event that a security breech does occur.")
st.write("Organize and conduct tests and “ethical hacks” of the existing security architecture.")
st.write("Monitor the network and provide early warning of abnormalities or problems.")
st.write("Upgrade systems regularly to remain competitive in the field of security.")
st.write("Communicate the system status and keep users informed of downtime or changes to the system.")
st.subheader("Salary")
st.write("According to online sources , the average salary for a Information Security Specialist is Rs. 10,03,608 per year in India.")