import streamlit as st
st.header("Networking Engineer")
st.write("tworking Engineer will be responsible for maintaining and administering our company's computer networks. Primary duties will include maintenance of computer networks, hardware, software, and other related systems, performing disaster recovery operations, protecting data, software, and hardware from attacks, and replacing faulty network hardware components when necessary. Networking Engineers will also be working closely with the users of our network in order to identify potential issues and fix existing problems.")
st.write("Networking Engineer ensures the integrity of high availability network infrastructure to provide maximum performance for your users. Networking Engineer work's internally as part of an organisation's IT support team, or externally as part of an outsourced IT networking consultancy firm working with a number of clients.")
st.subheader("Skills required")
st.write("Strong understanding of network infrastructure and network hardware.")
st.write("Ability to think through problems and visualize solutions.")
st.write("Ability to implement, administer, and troubleshoot network infrastructure devices, including wireless access points, firewall, routers, switches, controllers.")
st.write("Ability to create accurate network diagrams and documentation for design and planning network communication systems.")
st.write("Provides specific detailed information for hardware and software selection.")
st.write("Ability to quickly learn new or unfamiliar technology and products using documentation and internet resources.")
st.write("Ability to work with all levels of staff within and outside of IT and outside the organization.")
st.subheader("Educational Requirements")
st.write("Network Engineer Requirements include having a bachelor’ degree in the field of computer science, information technology or something that is related to technology. They should have a solid understanding of the network infrastructure and hardware.There are a lot of specialist courses that can enable you to get the skills and knowledge needed regarding networking certifications. Some of these are CCIE (Cisco), CCNP (Cisco), JNCIE-ENT (Juniper), Network+ (CompTIA), WCNA (Wireshark).")
st.subheader("Duties and Responsibilities")
st.write("Maintaining and administering computer networks and related computing environments including systems software, applications software, hardware, and configurations.")
st.write("Performing disaster recovery operations and data backups when required.")
st.write("Protecting data, software, and hardware by coordinating, planning, and implementing network security measures.")
st.write("Troubleshooting, diagnosing, and resolving hardware, software, and other network and system problems.")
st.write("Maintaining, configuring, and monitoring virus protection software and email applications.")
st.write("gning, configuring, and testing networking software, computer hardware, and operating system software.")
st.subheader("Salary")
st.write("The average salary for a Network Engineer is ₹4,68,500 per year. A Network Engineer can expect an average starting salary of ₹1,65,000. The highest salaries can exceed ₹9,00,000.")