import streamlit as st
st.header("Project Manager")
st.write("A Project Manager is responsible for planning, overseeing and leading projects from ideation through to completion. This is a senior role at an organisation and requires interaction with a range of internal and external stakeholders, most often managing several moving project parts simultaneously. An ideal Project Manager job description should capture the nuances and variation of this senior role, seeking multi-skilled and highly capable candidates.")
st.write("Project managers in information technology (IT) are tasked with planning certain types of projects within a company and ensuring that they are executed and on-track through every stage of the process. This job may require daily evaluations of employees, as well as leadership and motivation, in order to achieve particular goals.")
st.write("IT project managers must ensure that employees have the same shared vision and goals for projects while being assigned specific duties. Problem-solving may be necessary when projects are not going as planned, and they are usually given budgets for projects and must ensure that all parties involved are adhering to financial limits.")
st.write("These project managers oversee projects until they are finished, and evaluate them to determine whether follow-up projects are necessary and what changes can be made for the future. This job may also involve overseeing various personnel and departments to ensure their collaboration. Some positions require certification, such as project management professional certification, and a bachelor’s degree or higher in information technology, computer science, or a related field may also be required. As this is a leadership position, many years of relevant experience are often necessary, and past leadership skills and duties should be demonstrated.")
st.subheader("Skills required")
st.write("Project Managers should possess high levels of the below skills to perform well in the role")
st.write("Written and verbal communication skills")
st.write("Capacity to manage high stress situations.")
st.write("Ability to multi-task and manage various project elements simultaneously")
st.write("Leadership skills.")
st.write("Big-picture thinking and vision.")
st.write("Attention to detail.")
st.subheader("Educational Requirements")
st.write("A Project Manager job description could include degrees in any of the following fields:")
st.write("Engineering")
st.write("IT or Computer Science")
st.write("Business or Business Administration")
st.write("Management")
st.subheader("Duties and Responsibilities")
st.write("As a role that focuses on completing a project as efficiently and promptly as possible, expect to see any of the following duties and responsibilities in a Project Manager job description:")
st.write("Leading project planning sessions")
st.write("Coordinating staff and internal resources.")
st.write("Managing relationships with clients and stakeholders")
st.write("Designing and signing off on contracts")
st.write("Overseeing all incoming and outgoing project documentation")
st.write("Conducting project review and creating detailed reports for executive staff")
st.write("Optimising and improving processes and the overall approach where necessary")
st.write("Managing large and diverse teams")
st.subheader("Salary")
st.write("An entry-level Project Manager, Information Technology (IT) with less than 1 year experience can expect to earn an average total compensation (includes tips, bonus, and overtime pay) of ₹396,635 based on 57 salaries. An early career Project Manager, Information Technology (IT) with 1-4 years of experience earns an average total compensation of ₹663,530 based on 197 salaries. A mid-career Project Manager, Information Technology (IT) with 5-9 years of experience earns an average total compensation of ₹1,216,673 based on 389 salaries. An experienced Project Manager, Information Technology (IT) with 10-19 years of experience earns an average total compensation of ₹1,721,476 based on 1,368 salaries. In their late career (20 years and higher), employees earn an average total compensation of ₹2,306,765.")