import streamlit as st
st.header("Software Developer")
st.write("Software Developer design, develop, and test software and applications for computers. The main duties and responsibilities of software developer include directing and participating in programming activities, monitoring, and evaluating system performance, and designing and implementing new programs and features.")
st.write("A Java, C#, .Net, C, Sybase and Oracle Software Developer is generally responsible for the development, design and implementation of new or modified software products or ongoing business projects. Typically sitting within the IT team of a business, a Software Developer will be involved in liaising with the Business Analysts and Development Managers to ensure software projects meet requirements.")
st.subheader("Skills required")
st.write("To be successful in this role, you will need extensive knowledge of programming languages and the software development life-cycle.")
st.write("Ability to develop unit testing of code components or complete applications.")
st.write("Must be a full-stack developer and understand concepts of software engineering.")
st.write("Experience working on a variety of software development projects.Experience working on a variety of software development projects.")
st.write("Deep programming language knowledge.")
st.write("Knowledge of the software development life-cycle.")
st.write("Analyze code for weaknesses and errors, and present detailed plans to improve them.")
st.write("Outstanding collaboration and communication skills are essential.")
st.write("Experience developing software utilizing various coding languages including Java, C++, PHP and more")
st.subheader("Educational Requirements")
st.write("A degree and a technical background should be required to gain a Software Developer role. Degrees in the following subjects should be highlighted as particularly advantageous such as Computer Science , Computer Software Engineering, Software Programming and Development, Engineering.")
st.subheader("Duties and Responsibilities")
st.write("Directing system testing and validation procedures.")
st.write("Professionally maintain all software and create updates regularly to address customer and company concerns.")
st.write("Working with customers or departments on technical issues including software system design and maintenance.")
st.write("Designing and developing software systems using scientific analysis and mathematical models to predict and measure outcomes and design consequences.")
st.write("Directing software programming and documentation development.")
st.write("Consulting with departments or customers on project status and proposals")
st.write("Consulting with engineering staff to evaluate software hardware interfaces and develop specifications and performance requirements.")
st.write("Preparing reports on programming project specifications, activities, or status.")
st.subheader("Salary")
st.write("The national average salary for a Software Developer is Rs. 6,00,000 in India. It varies from range Rs. 6,00,000 - Rs. 11,00,000 depending upon Companies")