import streamlit as st
st.header("Software Tester")
st.write("Software Testers are responsible for the quality of software development and deployment. They are involved in performing automated and manual tests to ensure the software created by developers is fit for purpose. Some of the duties include analysis of software, and systems, mitigate risk and prevent software issues.")
st.write("A software tester is responsible for designing test scenarios for software usability, running these tests, and preparing reports on the effectiveness and defects to the production team. A software tester is also known as a software test engineer or a quality assurance (QA) tester.")
st.subheader("Skills Required")
st.write("One should have a working knowledge of software and test design, the capability to run through tests, and the ability to analyze the results. Ultimately, the software tester should be result-driven, have good communication skills, and up-to-date knowledge of software programming and software test design.")
st.write("Up-to-date knowledge of software test design and testing methodologies.")
st.write("Working knowledge of test techniques and compatibility with various software programs.")
st.write("Working knowledge of test techniques and compatibility with various software programs.")
st.write("Excellent communication and critical thinking skills.")
st.write("A passion for working with technology.")
st.subheader("Educational Requirements")
st.write("Academic background of a software tester should be in Computer Science. A BTech/ B.E., MCA, BCA, BSc- Computers, will land a job quickly.If person does not hold any of these degrees, then they must complete a software testing certification like ISTQB and CSTE which help you learn Software Development/ Test Life Cycle and other testing methodologies.")
st.subheader("Duties and Responsibilities")
st.write("Reviewing software requirements and preparing test scenarios.")
st.write("Executing tests on software usability.")
st.write("Analyzing test results on database impacts, errors or bugs, and usability.")
st.write("Interacting with clients to understand product requirements.")
st.write("Execute all levels of testing (System, Integration, and Regression).")
st.write("Participating in design reviews and providing input on requirements, product design, and potential problems.")
st.subheader("Salary")
st.write("Compensation of a software tester varies from company to company. Average Software testing career package in India is Rs 247,315 - Rs 449,111.")