import streamlit as st
st.header("Technical Writer")
st.write("Technical Writers are responsible for prepare instruction manuals and articles with the main goal to communicate complex, technical information more easily. They also develop, gather, and disseminate technical information among customers, designers, and manufacturers. Technical Writers are responsible for producing high-quality and understandable documentation with the goal to improve the success of our products.")
st.subheader("Skills Required")
st.write("Ability to translate highly technical information into easily understandable information for customers.")
st.write("Creative skills and usage of photographs, drawings, diagrams, animation, and charts that increase users understanding.")
st.write("Excellent written skills in English.")
st.write("Excellent communication and teamwork skills, including willingness and ability to consult with subject matter experts from engineering, support, and product management.")
st.write("Enjoys working as part of a team in a collaborative environment.")
st.write("Attention to detail with a creative eye.")
st.subheader("Educational Requirements")
st.write("A college degree is usually required for a position as a technical writer. In addition, knowledge of or experience with a technical subject, such as science or engineering, is beneficial. Employers generally prefer candidates who have a bachelor’s degree in English or another communications-related subject. Technical writing jobs may require candidates to have both a degree and knowledge of a technical field, such as engineering, computer science.")
st.subheader("Duties and Responsibilities")
st.write("Technical writers create paper-based and digital operating instructions, how-to manuals, assembly instructions, and “frequently asked questions” pages to help technical support staff, consumers, and other users within a company or an industry.")
st.write("Write for a variety of audiences, from non-technical end users to programmers, system administrators, and integrators.")
st.write("Prepare, review, revise, and maintain technical documents, including software and systems engineering, system operations, testing, and user documentation.")
st.write("Gather and analyze technical and product information from various sources to document new or changing product functionality.")
st.write("Identify problem areas or structural deficiencies and proactively contribute to their improvement.")
st.write("Update existing docs to reflect changes to functionality.")
st.write("Test both the product and its documentation for accuracy and consistency.")
st.subheader("Salary")
st.write("According to online sources, The national average salary for a Technical Writer is Rs.5,99,007 in India. ")